remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Demo data science portfolio
author: Lauren Trichtinger
description: An example of a data science portfolio showcasing coursework and projects.
